sudo: true
dist: trusty

before_install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo --channel=extended

script:
  - /snap/bin/hugo

deploy:
  local_dir: public
  repo: bgruszka/bgruszka.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  name: "bgruszka"
  on:
    branch: master
